sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t karolniedziela/lab8 -f Dockerfile.dev .

script:
  - docker run -e CI=true karolniedziela/lab8 npm run test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: fibonacci-lab8
on:
  repo: karolNiedziela/Lab8
