sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t karolniedziela/lab8 -f Dockerfile.dev .

script:
  - docker run -e CI=true karolniedziela/lab8 npm run test

deploy:
  provider: heroku
  api_key:
    secure: dXCa2UoKCis0T3FqWzIiAUDLHVt31090lPOv+GkEpUcKbDsXSyn0tmN7j8yh/bHH4msvfFrEAt/muCfB87s/fMkOZSE1SvKgjA2RJuIcbLTNxlLu+JIxUR9sCNdXXEydH2SVN8iTKpJQ8YnKPVArpDmr++WzM2pLUPjZg/2v9dl8IwG4LsRJGgZFwEvhLbxrJVv94rlPTd7LlyQrlOS6ORcS+i3NCjkUtKZUZTcfnvUM5QxiazilSkRQljc98sq6ECaqCvqto+rRezOlDOExWuihXNh1ft6OARkSU3nU+SuMWnXyaUHULVpZAZEuNUqJQTlFPmHzXkjtJj5HtUDKKWHKFKKFgXzU/VUgRJ0beDpU9Cf76BY6zKFzkUHrjdBMJIvYmNAmK6jMx+AWdThcTeDL7exztCQEADZCj5FwwEz7jaaYq09YwP0CVMzHUlEmBa6ic1qQhwimcGFr23mz8oj2hYomMF/9/Ov9HIkAPPD8PklDRbVkX+p4ZxMXY2IWqJAuXSse/91La2t7aayi4IeAhkvZ19cakKemMwywL7re6iZhnactihLZ+milSxWrywZuC0zWK48jezQC6F2Za3DW9ZLM0PQy4Ylo0cNyo9QlA3akCsCsp5PUtV1PuVnCy3IgQ95JXN1/UyXLEm3cEBWY/v9W8X7dJNKVrF+DDOE=
  app: fibonacci-lab8
true:
  repo: karolNiedziela/Lab8
