sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t karolNiedziela/Lab8 -f Dockerfile.dev .

script:
  - docker run -e CI=true karolNiedziela/Lab8 ng test --karma-config karma.conf.js fibonacci
