FROM node:alpine

# install chrome for tests
RUN apk add chromium

WORKDIR /app

ENV CHROME_BIN='/usr/bin/chromium-browser'
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./

RUN npm install
RUN npm install -g @angular/cli

COPY . .

CMD ["npm" "run" "start"]
