FROM node:16-alpine

# install chrome for tests
RUN apk add chromium

WORKDIR /app

ENV CHROME_BIN='/usr/bin/chromium-browser'
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./

RUN npm install
RUN npm install -g @angular/cli

COPY . ./app

EXPOSE 4200

CMD ng serve --host 0.0.0.0
